### PR TITLE
timeout config

### PR DESCRIPTION
**Pull request by JasonLing95**
- add timeout parameter to address timeout issue in Genetics Ark

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`docker-compose.yml` line 10 at r1](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2#-NJei99a76MZaZ_pewVn:-NJei99a76MZaZ_pewVo:bt1o3wk) ([raw file](https://github.com/eastgenomics/nginx-proxy/blob/b8edb8ef18e39e60f8ba54260201ff9bafa53eb5/docker-compose.yml#L10)):*
> ```YAML
>     volumes:
>       - /var/run/docker.sock:/tmp/docker.sock:ro
>       - /home/jason/github/nginx-proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
> ```

does this need to be different for deploying?



_Code quote:_
```YAML
 /home/jason/github/nginx-proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`docker-compose.yml` line 10 at r1](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2#-NJei99a76MZaZ_pewVn:-NJejmnxCwifLe3_xXLI:b-w53nwn) ([raw file](https://github.com/eastgenomics/nginx-proxy/blob/b8edb8ef18e39e60f8ba54260201ff9bafa53eb5/docker-compose.yml#L10)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this need to be different for deploying?
</blockquote></details>

nope. just need restarting with a custom proxy.conf with `proxy_read_timeout 300;`. It's currently re-deployed on dev. the proxy.conf (custom config) is in /appdata/ngx_proxy

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/nginx-proxy/2#-:-NJekOt0-XLU_QXYKlJD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
